spring:
  application:
    name: adaptive-learning-path-api
  datasource:
    url: jdbc:h2:file:./data/learningpathdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8000

app:
  cors:
    allowed-origins:  http://localhost:4200
